---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: CICD-K8S
spec:
  replicas: 2
  selector:
    matchLabels:
      app: CICD-K8S
  template:
    metadata:
      labels:
        app: CICD-K8S
    spec:
      containers:
      - name: CICD-K8S-cont
        image: charansuryakilana/ez_deploy_prototype:image1
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: CICD-K8S-service
spec:
  selector:
    app: CICD-K8S
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
